CREATE TABLE price_catalog_items (
	sku TEXT PRIMARY KEY,
	service_code TEXT NOT NULL,
	service_name TEXT NOT NULL,
	product_family TEXT NOT NULL,
	usage_type TEXT NOT NULL,
	operation TEXT NOT NULL,
	region_code TEXT NOT NULL,
	unit TEXT NOT NULL,
	rate_micros INTEGER NOT NULL CHECK (rate_micros >= 0),
	currency_code TEXT NOT NULL CHECK (length(currency_code) = 3),
	effective_date TEXT NOT NULL,
	price_source TEXT NOT NULL CHECK (price_source IN ('synthetic', 'aws_price_list_snapshot', 'instructor_override')),
	pricing_formula TEXT NOT NULL,
	notes TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX idx_price_catalog_items_service_region
ON price_catalog_items (service_code, region_code);

INSERT INTO price_catalog_items (
	sku,
	service_code,
	service_name,
	product_family,
	usage_type,
	operation,
	region_code,
	unit,
	rate_micros,
	currency_code,
	effective_date,
	price_source,
	pricing_formula,
	notes
) VALUES
	(
		'SIM-EC2-T3-MEDIUM-HR',
		'AmazonEC2',
		'Amazon EC2',
		'Compute Instance',
		'instance-hours:t3.medium',
		'RunInstances',
		'us-east-1',
		'InstanceHour',
		41600,
		'USD',
		'2026-01-01',
		'synthetic',
		'usage_quantity * rate',
		'Synthetic Linux t3.medium instance-hour rate for deterministic simulator scenarios.'
	),
	(
		'SIM-EBS-GP3-GBMO',
		'AmazonEBS',
		'Amazon EBS',
		'Block Storage',
		'storage:gp3-gb-month',
		'VolumeStorage',
		'us-east-1',
		'GBMonth',
		80000,
		'USD',
		'2026-01-01',
		'synthetic',
		'daily_gb_month_quantity * rate',
		'Synthetic gp3 volume storage rate prorated from daily GB-month metering.'
	),
	(
		'SIM-S3-STANDARD-GBMO',
		'AmazonS3',
		'Amazon S3',
		'Object Storage',
		'storage:standard-gb-month',
		'StandardStorage',
		'us-east-1',
		'GBMonth',
		23000,
		'USD',
		'2026-01-01',
		'synthetic',
		'storage_gb_month_quantity * rate',
		'Synthetic S3 Standard storage GB-month rate.'
	),
	(
		'SIM-S3-PUT-1K',
		'AmazonS3',
		'Amazon S3',
		'API Request',
		'requests:put-1k',
		'PutObject',
		'us-east-1',
		'ThousandRequests',
		5000,
		'USD',
		'2026-01-01',
		'synthetic',
		'(request_count / 1000) * rate',
		'Synthetic S3 PUT, COPY, POST, and LIST request rate per 1,000 requests.'
	),
	(
		'SIM-S3-GET-1K',
		'AmazonS3',
		'Amazon S3',
		'API Request',
		'requests:get-1k',
		'GetObject',
		'us-east-1',
		'ThousandRequests',
		400,
		'USD',
		'2026-01-01',
		'synthetic',
		'(request_count / 1000) * rate',
		'Synthetic S3 GET and SELECT request rate per 1,000 requests.'
	),
	(
		'SIM-S3-RETRIEVAL-GB',
		'AmazonS3',
		'Amazon S3',
		'Data Retrieval',
		'retrieval:standard-gb',
		'GetObjectRetrieval',
		'us-east-1',
		'GB',
		10000,
		'USD',
		'2026-01-01',
		'synthetic',
		'retrieved_gb * rate',
		'Synthetic object retrieval rate for lessons that compare storage classes.'
	),
	(
		'SIM-LAMBDA-REQUESTS-1M',
		'AWSLambda',
		'AWS Lambda',
		'Serverless Compute',
		'requests:lambda-1m',
		'Invoke',
		'us-east-1',
		'MillionRequests',
		200000,
		'USD',
		'2026-01-01',
		'synthetic',
		'(request_count / 1000000) * rate',
		'Synthetic Lambda invocation request rate per 1,000,000 requests.'
	),
	(
		'SIM-LAMBDA-GBS',
		'AWSLambda',
		'AWS Lambda',
		'Serverless Compute',
		'compute:lambda-gb-second',
		'Invoke',
		'us-east-1',
		'GBSecond',
		17,
		'USD',
		'2026-01-01',
		'synthetic',
		'gb_seconds * rate',
		'Synthetic Lambda duration rate rounded to whole microdollars for deterministic math.'
	),
	(
		'SIM-RDS-T3-MEDIUM-HR',
		'AmazonRDS',
		'Amazon RDS',
		'Managed Database',
		'instance-hours:db.t3.medium',
		'CreateDBInstance',
		'us-east-1',
		'InstanceHour',
		68000,
		'USD',
		'2026-01-01',
		'synthetic',
		'usage_quantity * rate',
		'Synthetic single-AZ db.t3.medium database instance-hour rate.'
	),
	(
		'SIM-RDS-STORAGE-GBMO',
		'AmazonRDS',
		'Amazon RDS',
		'Database Storage',
		'storage:rds-gp3-gb-month',
		'DatabaseStorage',
		'us-east-1',
		'GBMonth',
		115000,
		'USD',
		'2026-01-01',
		'synthetic',
		'daily_gb_month_quantity * rate',
		'Synthetic RDS storage GB-month rate.'
	),
	(
		'SIM-NAT-GATEWAY-HR',
		'AmazonVPCNATGateway',
		'NAT Gateway',
		'Network Appliance',
		'nat-gateway-hours',
		'NatGateway',
		'us-east-1',
		'GatewayHour',
		45000,
		'USD',
		'2026-01-01',
		'synthetic',
		'gateway_hours * rate',
		'Synthetic NAT Gateway hourly charge for shared-services scenarios.'
	),
	(
		'SIM-NAT-GATEWAY-GB',
		'AmazonVPCNATGateway',
		'NAT Gateway',
		'Network Appliance',
		'nat-gateway-data-processed-gb',
		'NatGatewayDataProcessing',
		'us-east-1',
		'GB',
		45000,
		'USD',
		'2026-01-01',
		'synthetic',
		'processed_gb * rate',
		'Synthetic NAT Gateway data processing charge.'
	),
	(
		'SIM-CWLOGS-INGEST-GB',
		'AmazonCloudWatchLogs',
		'CloudWatch Logs',
		'Log Management',
		'logs-ingestion-gb',
		'PutLogEvents',
		'us-east-1',
		'GB',
		500000,
		'USD',
		'2026-01-01',
		'synthetic',
		'ingested_gb * rate',
		'Synthetic CloudWatch Logs ingestion rate.'
	),
	(
		'SIM-CWLOGS-STORAGE-GBMO',
		'AmazonCloudWatchLogs',
		'CloudWatch Logs',
		'Log Management',
		'logs-storage-gb-month',
		'LogStorage',
		'us-east-1',
		'GBMonth',
		30000,
		'USD',
		'2026-01-01',
		'synthetic',
		'stored_gb_month_quantity * rate',
		'Synthetic CloudWatch Logs retained storage rate.'
	),
	(
		'SIM-DATAXFER-INTERNET-GB',
		'AWSDataTransfer',
		'AWS Data Transfer',
		'Data Transfer',
		'data-transfer-out-internet-gb',
		'DataTransferOut',
		'global',
		'GB',
		90000,
		'USD',
		'2026-01-01',
		'synthetic',
		'transferred_gb * rate',
		'Synthetic internet data transfer out rate.'
	),
	(
		'SIM-DATAXFER-INTERREGION-GB',
		'AWSDataTransfer',
		'AWS Data Transfer',
		'Data Transfer',
		'data-transfer-inter-region-gb',
		'InterRegionDataTransfer',
		'global',
		'GB',
		20000,
		'USD',
		'2026-01-01',
		'synthetic',
		'transferred_gb * rate',
		'Synthetic inter-region data transfer rate.'
	),
	(
		'SIM-SUPPORT-BUSINESS-PCT',
		'AWSSupport',
		'AWS Support',
		'Support',
		'support-business-eligible-usd',
		'BusinessSupport',
		'global',
		'EligibleUSD',
		100000,
		'USD',
		'2026-01-01',
		'synthetic',
		'eligible_monthly_cost * rate_with_minimum',
		'Synthetic Business Support rate: 10 percent of eligible monthly charges with a future minimum rule.'
	),
	(
		'SIM-MARKETPLACE-SECURITY-MONTH',
		'AWSMarketplace',
		'AWS Marketplace',
		'Marketplace Subscription',
		'marketplace-security-tool-month',
		'MonthlySubscription',
		'global',
		'SubscriptionMonth',
		250000000,
		'USD',
		'2026-01-01',
		'synthetic',
		'subscription_months * rate',
		'Synthetic third-party security tool subscription for non-AWS seller scenarios.'
	);

PRAGMA user_version = 2;
